-- WorkZen HRMS - Initial Seed Data
-- Run this in pgAdmin Query Tool to populate initial data

-- Insert Roles
INSERT INTO roles (name, description) VALUES
('Admin', 'Full system access and management'),
('Manager', 'Department management and approvals'),
('Employee', 'Standard employee access'),
('HR', 'Human Resources management')
ON CONFLICT (name) DO NOTHING;

-- Insert Departments
INSERT INTO departments (name, description) VALUES
('Human Resources', 'HR and employee management'),
('Information Technology', 'IT and software development'),
('Finance', 'Financial management and accounting'),
('Operations', 'Business operations and logistics'),
('Sales', 'Sales and business development'),
('Marketing', 'Marketing and communications')
ON CONFLICT (name) DO NOTHING;

-- Insert Designations
INSERT INTO designations (name, description) VALUES
('CEO', 'Chief Executive Officer'),
('CTO', 'Chief Technology Officer'),
('CFO', 'Chief Financial Officer'),
('Manager', 'Department Manager'),
('Team Lead', 'Team Leader'),
('Senior Developer', 'Senior Software Developer'),
('Developer', 'Software Developer'),
('Junior Developer', 'Junior Software Developer'),
('HR Manager', 'Human Resources Manager'),
('HR Executive', 'Human Resources Executive'),
('Accountant', 'Financial Accountant'),
('Sales Executive', 'Sales Executive'),
('Marketing Executive', 'Marketing Executive')
ON CONFLICT (name) DO NOTHING;

-- Insert Leave Types
INSERT INTO leave_types (name, max_days, carry_forward) VALUES
('Sick Leave', 12, false),
('Casual Leave', 12, true),
('Earned Leave', 15, true),
('Maternity Leave', 180, false),
('Paternity Leave', 15, false),
('Unpaid Leave', 0, false),
('Compensatory Off', 0, true)
ON CONFLICT (name) DO NOTHING;

-- Verify inserted data
SELECT 'Roles' as table_name, COUNT(*) as count FROM roles
UNION ALL
SELECT 'Departments', COUNT(*) FROM departments
UNION ALL
SELECT 'Designations', COUNT(*) FROM designations
UNION ALL
SELECT 'Leave Types', COUNT(*) FROM leave_types;

-- Sample Admin User (password: admin123)
-- Password hash generated with bcrypt for 'admin123'
INSERT INTO users (name, email, password_hash, role_id, department_id, designation_id, base_salary, phone, is_active)
VALUES (
  'System Admin',
  'admin@workzen.com',
  '$2b$10$rKZLvXz5JGKqN8YqF5xGxOYqF5xGxOYqF5xGxOYqF5xGxOYqF5xGxO', -- This is a placeholder, will be generated by API
  (SELECT id FROM roles WHERE name = 'Admin'),
  (SELECT id FROM departments WHERE name = 'Information Technology'),
  (SELECT id FROM designations WHERE name = 'CTO'),
  100000.00,
  '+1234567890',
  true
)
ON CONFLICT (email) DO NOTHING;

-- Display summary
SELECT 
  'Database seeded successfully!' as message,
  (SELECT COUNT(*) FROM roles) as roles,
  (SELECT COUNT(*) FROM departments) as departments,
  (SELECT COUNT(*) FROM designations) as designations,
  (SELECT COUNT(*) FROM leave_types) as leave_types,
  (SELECT COUNT(*) FROM users) as users;
